using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Security;
using System.Text;
using System.Windows.Forms.DataVisualization.Charting;

namespace WindowsFormsApp2
{
    internal static class ManagedXlsxWriter
    {
        private const string SpreadsheetNs = "http://schemas.openxmlformats.org/spreadsheetml/2006/main";
        private const string RelationshipNs = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
        private const string PackageRelationshipNs = "http://schemas.openxmlformats.org/package/2006/relationships";
        private const string DrawingNs = "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing";
        private const string DrawingMainNs = "http://schemas.openxmlformats.org/drawingml/2006/main";

        private sealed class SheetCell
        {
            public int Column { get; set; }
            public string Value { get; set; }
            public int StyleIndex { get; set; }
        }

        private sealed class SheetRow
        {
            public int RowNumber { get; set; }
            public double Height { get; set; }
            public List<SheetCell> Cells { get; } = new List<SheetCell>();
        }

        public static void ExportReport(string outputPath, string reportTitle, DataTable reportData, DataTable chartData, string chartTitle, string logoIcoPath)
        {
            var logoBytes = LoadPngBytesFromIcon(logoIcoPath);
            var chartBytes = CreateChartImage(chartData, chartTitle);

            var sheet1Rows = BuildReportSheetRows(reportTitle, reportData);
            var sheet2Rows = BuildChartSheetRows(chartTitle, chartData);

            using (var fileStream = new FileStream(outputPath, FileMode.Create, FileAccess.Write, FileShare.None))
            using (var archive = new ZipArchive(fileStream, ZipArchiveMode.Create, false))
            {
                WriteEntry(archive, "[Content_Types].xml", BuildContentTypes());
                WriteEntry(archive, "_rels/.rels", BuildRootRels());
                WriteEntry(archive, "xl/workbook.xml", BuildWorkbookXml());
                WriteEntry(archive, "xl/_rels/workbook.xml.rels", BuildWorkbookRels());
                WriteEntry(archive, "xl/styles.xml", BuildStylesXml());
                WriteEntry(archive, "xl/worksheets/sheet1.xml", BuildWorksheetXml(sheet1Rows, true, false));
                WriteEntry(archive, "xl/worksheets/sheet2.xml", BuildWorksheetXml(sheet2Rows, true, true));
                WriteEntry(archive, "xl/worksheets/_rels/sheet1.xml.rels", BuildSheetRels("drawing1.xml"));
                WriteEntry(archive, "xl/worksheets/_rels/sheet2.xml.rels", BuildSheetRels("drawing2.xml"));
                WriteEntry(archive, "xl/drawings/drawing1.xml", BuildDrawingXml("rId1", 7, 0, 1_000_000, 1_000_000));
                WriteEntry(archive, "xl/drawings/drawing2.xml", BuildDrawingXml("rId1", 1, 1, 5_600_000, 3_200_000));
                WriteEntry(archive, "xl/drawings/_rels/drawing1.xml.rels", BuildDrawingRels("../media/image1.png"));
                WriteEntry(archive, "xl/drawings/_rels/drawing2.xml.rels", BuildDrawingRels("../media/image2.png"));
                WriteBytes(archive, "xl/media/image1.png", logoBytes);
                WriteBytes(archive, "xl/media/image2.png", chartBytes);
            }
        }

        private static List<SheetRow> BuildReportSheetRows(string reportTitle, DataTable data)
        {
            var rows = new List<SheetRow>();

            rows.Add(Row(1, 28, Cell(1, "VaccineCare Information System", 1)));
            rows.Add(Row(2, 20, Cell(1, "Generated report package", 7)));
            rows.Add(Row(4, 22, Cell(1, "Generated By:", 2), Cell(2, "____________________", 6)));
            rows.Add(Row(5, 22, Cell(1, "Signature:", 2), Cell(2, "____________________", 6)));
            rows.Add(Row(7, 26, Cell(1, reportTitle, 3)));
            rows.Add(Row(9, 24, Cell(1, "Report Data", 3)));

            var headerRow = new SheetRow { RowNumber = 10, Height = 24 };
            for (int column = 0; column < data.Columns.Count; column++)
            {
                headerRow.Cells.Add(Cell(column + 1, data.Columns[column].ColumnName, 4));
            }
            rows.Add(headerRow);

            for (int row = 0; row < data.Rows.Count; row++)
            {
                var sheetRow = new SheetRow { RowNumber = row + 11, Height = 22 };
                for (int column = 0; column < data.Columns.Count; column++)
                {
                    sheetRow.Cells.Add(Cell(column + 1, FormatValue(data.Rows[row][column]), 5));
                }
                rows.Add(sheetRow);
            }

            return rows;
        }

        private static List<SheetRow> BuildChartSheetRows(string chartTitle, DataTable chartData)
        {
            var rows = new List<SheetRow>
            {
                Row(1, 28, Cell(1, "Graph Visualization", 1)),
                Row(2, 22, Cell(1, chartTitle, 7)),
                Row(4, 24, Cell(1, chartData.Columns[0].ColumnName, 4), Cell(2, chartData.Columns[1].ColumnName, 4))
            };

            for (int row = 0; row < chartData.Rows.Count; row++)
            {
                rows.Add(Row(row + 5, 22, Cell(1, FormatValue(chartData.Rows[row][0]), 5), Cell(2, FormatValue(chartData.Rows[row][1]), 5)));
            }

            return rows;
        }

        private static SheetRow Row(int rowNumber, params SheetCell[] cells)
        {
            return Row(rowNumber, 0, cells);
        }

        private static SheetRow Row(int rowNumber, double height, params SheetCell[] cells)
        {
            var row = new SheetRow { RowNumber = rowNumber, Height = height };
            row.Cells.AddRange(cells);
            return row;
        }

        private static SheetCell Cell(int column, string value, int styleIndex = 0)
        {
            return new SheetCell { Column = column, Value = value ?? string.Empty, StyleIndex = styleIndex };
        }

        private static string FormatValue(object value)
        {
            if (value == null || value == DBNull.Value)
            {
                return string.Empty;
            }

            if (value is DateTime dateTime)
            {
                return dateTime.ToString("yyyy-MM-dd");
            }

            return Convert.ToString(value) ?? string.Empty;
        }

        private static byte[] LoadPngBytesFromIcon(string iconPath)
        {
            if (string.IsNullOrEmpty(iconPath) || !File.Exists(iconPath))
            {
                return CreatePlaceholderPng();
            }

            using (var icon = new Icon(iconPath))
            using (var bitmap = icon.ToBitmap())
            using (var stream = new MemoryStream())
            {
                bitmap.Save(stream, ImageFormat.Png);
                return stream.ToArray();
            }
        }

        private static byte[] CreatePlaceholderPng()
        {
            using (var bitmap = new Bitmap(1, 1))
            using (var stream = new MemoryStream())
            {
                bitmap.SetPixel(0, 0, Color.Transparent);
                bitmap.Save(stream, ImageFormat.Png);
                return stream.ToArray();
            }
        }

        private static byte[] CreateChartImage(DataTable chartData, string chartTitle)
        {
            using (var chart = new Chart())
            {
                chart.Width = 900;
                chart.Height = 420;
                chart.BackColor = Color.White;

                var chartArea = new ChartArea("Main");
                chartArea.BackColor = Color.White;
                chartArea.BorderColor = Color.FromArgb(214, 219, 224);
                chartArea.BorderWidth = 1;
                chartArea.AxisX.MajorGrid.LineColor = Color.FromArgb(230, 234, 239);
                chartArea.AxisY.MajorGrid.LineColor = Color.FromArgb(230, 234, 239);
                chartArea.AxisX.LabelStyle.Font = new Font("Segoe UI", 9f);
                chartArea.AxisY.LabelStyle.Font = new Font("Segoe UI", 9f);
                chartArea.AxisX.LineColor = Color.FromArgb(160, 168, 176);
                chartArea.AxisY.LineColor = Color.FromArgb(160, 168, 176);
                chart.ChartAreas.Add(chartArea);

                var series = new Series("Series")
                {
                    ChartType = SeriesChartType.Column,
                    IsValueShownAsLabel = true,
                    ChartArea = "Main",
                    Font = new Font("Segoe UI", 9f),
                    Color = Color.FromArgb(0, 102, 204),
                    BorderColor = Color.FromArgb(0, 86, 179)
                };

                foreach (DataRow row in chartData.Rows)
                {
                    var label = FormatValue(row[0]);
                    var value = ParseDouble(row[1]);
                    series.Points.AddXY(label, value);
                }

                chart.Series.Add(series);
                chart.Titles.Add(new Title(chartTitle, Docking.Top, new Font("Segoe UI", 14f, FontStyle.Bold), Color.FromArgb(33, 37, 41)));

                using (var stream = new MemoryStream())
                {
                    chart.SaveImage(stream, ChartImageFormat.Png);
                    return stream.ToArray();
                }
            }
        }

        private static double ParseDouble(object value)
        {
            if (value == null || value == DBNull.Value)
            {
                return 0;
            }

            double result;
            if (double.TryParse(Convert.ToString(value), out result))
            {
                return result;
            }

            return 0;
        }

        private static void WriteEntry(ZipArchive archive, string path, string content)
        {
            var entry = archive.CreateEntry(path, CompressionLevel.Optimal);
            using (var stream = new StreamWriter(entry.Open(), new UTF8Encoding(false)))
            {
                stream.Write(content);
            }
        }

        private static void WriteBytes(ZipArchive archive, string path, byte[] content)
        {
            var entry = archive.CreateEntry(path, CompressionLevel.Optimal);
            using (var stream = entry.Open())
            {
                stream.Write(content, 0, content.Length);
            }
        }

        private static string BuildContentTypes()
        {
            return @"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<Types xmlns=""http://schemas.openxmlformats.org/package/2006/content-types"">
  <Default Extension=""rels"" ContentType=""application/vnd.openxmlformats-package.relationships+xml"" />
  <Default Extension=""xml"" ContentType=""application/xml"" />
  <Default Extension=""png"" ContentType=""image/png"" />
  <Override PartName=""/xl/workbook.xml"" ContentType=""application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"" />
  <Override PartName=""/xl/styles.xml"" ContentType=""application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"" />
  <Override PartName=""/xl/worksheets/sheet1.xml"" ContentType=""application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"" />
  <Override PartName=""/xl/worksheets/sheet2.xml"" ContentType=""application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"" />
  <Override PartName=""/xl/drawings/drawing1.xml"" ContentType=""application/vnd.openxmlformats-officedocument.drawing+xml"" />
  <Override PartName=""/xl/drawings/drawing2.xml"" ContentType=""application/vnd.openxmlformats-officedocument.drawing+xml"" />
</Types>";
        }

        private static string BuildRootRels()
        {
            return @"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<Relationships xmlns=""http://schemas.openxmlformats.org/package/2006/relationships"">
  <Relationship Id=""rId1"" Type=""http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"" Target=""xl/workbook.xml"" />
</Relationships>";
        }

        private static string BuildWorkbookXml()
        {
            return @"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<workbook xmlns=""http://schemas.openxmlformats.org/spreadsheetml/2006/main"" xmlns:r=""http://schemas.openxmlformats.org/officeDocument/2006/relationships"">
  <sheets>
    <sheet name=""Report Data"" sheetId=""1"" r:id=""rId1"" />
    <sheet name=""Graph Visualization"" sheetId=""2"" r:id=""rId2"" />
  </sheets>
</workbook>";
        }

        private static string BuildWorkbookRels()
        {
            return @"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<Relationships xmlns=""http://schemas.openxmlformats.org/package/2006/relationships"">
  <Relationship Id=""rId1"" Type=""http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"" Target=""worksheets/sheet1.xml"" />
  <Relationship Id=""rId2"" Type=""http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"" Target=""worksheets/sheet2.xml"" />
  <Relationship Id=""rId3"" Type=""http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"" Target=""styles.xml"" />
</Relationships>";
        }

        private static string BuildStylesXml()
        {
            return @"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<styleSheet xmlns=""http://schemas.openxmlformats.org/spreadsheetml/2006/main"">
  <fonts count=""5"">
    <font>
      <sz val=""11"" />
      <color rgb=""FF212529"" />
      <name val=""Segoe UI"" />
      <family val=""2"" />
    </font>
    <font>
      <b />
      <sz val=""16"" />
      <color rgb=""FF212529"" />
      <name val=""Segoe UI"" />
      <family val=""2"" />
    </font>
    <font>
      <b />
      <sz val=""11"" />
      <color rgb=""FF212529"" />
      <name val=""Segoe UI"" />
      <family val=""2"" />
    </font>
    <font>
      <b />
      <sz val=""11"" />
      <color rgb=""FFFFFFFF"" />
      <name val=""Segoe UI"" />
      <family val=""2"" />
    </font>
    <font>
      <sz val=""10"" />
      <color rgb=""FF586069"" />
      <name val=""Segoe UI"" />
      <family val=""2"" />
    </font>
  </fonts>
  <fills count=""5"">
    <fill><patternFill patternType=""none"" /></fill>
    <fill><patternFill patternType=""gray125"" /></fill>
    <fill><patternFill patternType=""solid""><fgColor rgb=""FFE8EEF5"" /><bgColor indexed=""64"" /></patternFill></fill>
    <fill><patternFill patternType=""solid""><fgColor rgb=""FF0066CC"" /><bgColor indexed=""64"" /></patternFill></fill>
    <fill><patternFill patternType=""solid""><fgColor rgb=""FFF8FAFC"" /><bgColor indexed=""64"" /></patternFill></fill>
  </fills>
  <borders count=""3"">
    <border><left /><right /><top /><bottom /><diagonal /></border>
    <border>
      <left style=""thin""><color rgb=""FFD6DBE0"" /></left>
      <right style=""thin""><color rgb=""FFD6DBE0"" /></right>
      <top style=""thin""><color rgb=""FFD6DBE0"" /></top>
      <bottom style=""thin""><color rgb=""FFD6DBE0"" /></bottom>
      <diagonal />
    </border>
    <border>
      <bottom style=""medium""><color rgb=""FF0066CC"" /></bottom>
      <diagonal />
    </border>
  </borders>
  <cellStyleXfs count=""1"">
    <xf numFmtId=""0"" fontId=""0"" fillId=""0"" borderId=""0"" />
  </cellStyleXfs>
  <cellXfs count=""8"">
    <xf numFmtId=""0"" fontId=""0"" fillId=""0"" borderId=""0"" xfId=""0"" />
    <xf numFmtId=""0"" fontId=""1"" fillId=""0"" borderId=""2"" xfId=""0"" applyFont=""1"" applyBorder=""1"" />
    <xf numFmtId=""0"" fontId=""2"" fillId=""0"" borderId=""0"" xfId=""0"" applyFont=""1"" />
    <xf numFmtId=""0"" fontId=""2"" fillId=""2"" borderId=""1"" xfId=""0"" applyFont=""1"" applyFill=""1"" applyBorder=""1"" />
    <xf numFmtId=""0"" fontId=""3"" fillId=""3"" borderId=""1"" xfId=""0"" applyFont=""1"" applyFill=""1"" applyBorder=""1"" />
    <xf numFmtId=""0"" fontId=""0"" fillId=""0"" borderId=""1"" xfId=""0"" applyBorder=""1"" />
    <xf numFmtId=""0"" fontId=""0"" fillId=""0"" borderId=""0"" xfId=""0"" applyAlignment=""1""><alignment horizontal=""left"" /></xf>
    <xf numFmtId=""0"" fontId=""4"" fillId=""0"" borderId=""0"" xfId=""0"" applyFont=""1"" />
  </cellXfs>
  <cellStyles count=""1"">
    <cellStyle name=""Normal"" xfId=""0"" builtinId=""0"" />
  </cellStyles>
</styleSheet>";
        }

        private static string BuildSheetRels(string target)
        {
            return $@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<Relationships xmlns=""http://schemas.openxmlformats.org/package/2006/relationships"">
  <Relationship Id=""rId1"" Type=""http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing"" Target=""../drawings/{target}"" />
</Relationships>";
        }

        private static string BuildDrawingRels(string target)
        {
            return $@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<Relationships xmlns=""http://schemas.openxmlformats.org/package/2006/relationships"">
  <Relationship Id=""rId1"" Type=""http://schemas.openxmlformats.org/officeDocument/2006/relationships/image"" Target=""{target}"" />
</Relationships>";
        }

        private static string BuildDrawingXml(string relId, int fromColumn, int fromRow, int widthEmu, int heightEmu)
        {
            return $@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<xdr:wsDr xmlns:xdr=""{DrawingNs}"" xmlns:a=""{DrawingMainNs}"" xmlns:r=""{RelationshipNs}"">
  <xdr:oneCellAnchor editAs=""oneCell"">
    <xdr:from>
      <xdr:col>{fromColumn}</xdr:col>
      <xdr:colOff>0</xdr:colOff>
      <xdr:row>{fromRow}</xdr:row>
      <xdr:rowOff>0</xdr:rowOff>
    </xdr:from>
    <xdr:ext cx=""{widthEmu}"" cy=""{heightEmu}"" />
    <xdr:pic>
      <xdr:nvPicPr>
        <xdr:cNvPr id=""0"" name=""Picture 1"" />
        <xdr:cNvPicPr>
          <a:picLocks noChangeAspect=""1"" />
        </xdr:cNvPicPr>
      </xdr:nvPicPr>
      <xdr:blipFill>
        <a:blip r:embed=""{relId}"" />
        <a:stretch>
          <a:fillRect />
        </a:stretch>
      </xdr:blipFill>
      <xdr:spPr>
        <a:xfrm>
          <a:off x=""0"" y=""0"" />
          <a:ext cx=""0"" cy=""0"" />
        </a:xfrm>
        <a:prstGeom prst=""rect"">
          <a:avLst />
        </a:prstGeom>
      </xdr:spPr>
    </xdr:pic>
    <xdr:clientData />
  </xdr:oneCellAnchor>
</xdr:wsDr>";
        }

        private static string BuildWorksheetXml(IEnumerable<SheetRow> rows, bool includeDrawing, bool chartSheet)
        {
            var sb = new StringBuilder();
            sb.AppendLine(@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>");
            sb.AppendLine($@"<worksheet xmlns=""{SpreadsheetNs}"" xmlns:r=""{RelationshipNs}"">");
            sb.AppendLine(@"  <sheetViews>");
            sb.AppendLine(@"    <sheetView workbookViewId=""0"">");
            sb.AppendLine(chartSheet
                ? @"      <pane ySplit=""4"" topLeftCell=""A5"" activePane=""bottomLeft"" state=""frozen"" />"
                : @"      <pane ySplit=""10"" topLeftCell=""A11"" activePane=""bottomLeft"" state=""frozen"" />");
            sb.AppendLine(@"    </sheetView>");
            sb.AppendLine(@"  </sheetViews>");
            sb.AppendLine(chartSheet ? BuildChartColumnsXml() : BuildReportColumnsXml());
            sb.AppendLine("  <sheetData>");

            foreach (var row in rows.OrderBy(r => r.RowNumber))
            {
                var height = row.Height > 0 ? $@" ht=""{row.Height}"" customHeight=""1""" : string.Empty;
                sb.AppendLine($@"    <row r=""{row.RowNumber}""{height}>");
                foreach (var cell in row.Cells.OrderBy(c => c.Column))
                {
                    var style = cell.StyleIndex > 0 ? $@" s=""{cell.StyleIndex}""" : string.Empty;
                    sb.AppendLine($@"      <c r=""{ColumnName(cell.Column)}{row.RowNumber}""{style} t=""inlineStr""><is><t xml:space=""preserve"">{Escape(cell.Value)}</t></is></c>");
                }
                sb.AppendLine("    </row>");
            }

            sb.AppendLine("  </sheetData>");
            if (!chartSheet)
            {
                sb.AppendLine(@"  <mergeCells count=""3"">");
                sb.AppendLine(@"    <mergeCell ref=""A1:F1"" />");
                sb.AppendLine(@"    <mergeCell ref=""A2:F2"" />");
                sb.AppendLine(@"    <mergeCell ref=""A7:F7"" />");
                sb.AppendLine(@"  </mergeCells>");
            }
            if (includeDrawing)
            {
                sb.AppendLine(@"  <drawing r:id=""rId1"" />");
            }
            sb.AppendLine("</worksheet>");
            return sb.ToString();
        }

        private static string BuildReportColumnsXml()
        {
            return @"  <cols>
    <col min=""1"" max=""1"" width=""14"" customWidth=""1"" />
    <col min=""2"" max=""2"" width=""22"" customWidth=""1"" />
    <col min=""3"" max=""3"" width=""22"" customWidth=""1"" />
    <col min=""4"" max=""4"" width=""18"" customWidth=""1"" />
    <col min=""5"" max=""5"" width=""18"" customWidth=""1"" />
    <col min=""6"" max=""6"" width=""22"" customWidth=""1"" />
    <col min=""7"" max=""7"" width=""20"" customWidth=""1"" />
    <col min=""8"" max=""8"" width=""14"" customWidth=""1"" />
    <col min=""9"" max=""9"" width=""14"" customWidth=""1"" />
  </cols>";
        }

        private static string BuildChartColumnsXml()
        {
            return @"  <cols>
    <col min=""1"" max=""1"" width=""28"" customWidth=""1"" />
    <col min=""2"" max=""2"" width=""14"" customWidth=""1"" />
    <col min=""3"" max=""8"" width=""16"" customWidth=""1"" />
  </cols>";
        }

        private static string ColumnName(int columnNumber)
        {
            var dividend = columnNumber;
            var columnName = string.Empty;

            while (dividend > 0)
            {
                var modulo = (dividend - 1) % 26;
                columnName = Convert.ToChar(65 + modulo) + columnName;
                dividend = (dividend - modulo) / 26;
            }

            return columnName;
        }

        private static string Escape(string value)
        {
            return SecurityElement.Escape(value) ?? string.Empty;
        }
    }
}
